In [ ]:
# first we import all the required modules 

In [2]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.model_selection import train_test_split

In [3]:
# then after importing the csv file we check if any examples have empty values for any of the selected attributes , on which they are dropped

In [4]:
df = pd.read_csv("games.csv",usecols=['opening_ply','turns','winner','black_rating','white_rating'])
df.dropna(
    axis=0,
    how='any',
    inplace=True
)

In [5]:
# Now For a classification model, we split the columns into X and Y , where X is the sample data with chosen features , and Y is the prediction classes

In [6]:
X = df.drop(['winner'],axis=1)
Y = df.drop(['turns','black_rating','white_rating','opening_ply'],axis=1)
print(X)
print(Y)

       turns  white_rating  black_rating  opening_ply
0         13          1500          1191            5
1         16          1322          1261            4
2         61          1496          1500            3
3         61          1439          1454            3
4         95          1523          1469            5
...      ...           ...           ...          ...
20053     24          1691          1220            2
20054     82          1233          1196            2
20055     35          1219          1286            3
20056    109          1360          1227            4
20057     78          1235          1339            3

[20058 rows x 4 columns]
      winner
0      white
1      black
2      white
3      white
4      white
...      ...
20053  white
20054  black
20055  white
20056  white
20057  black

[20058 rows x 1 columns]


In [7]:
X = X.to_numpy()
Y = Y.to_numpy()
print(X.shape)

(20058, 4)


In [8]:
# Calculating better attribute to predict ( Difference in rating)

In [9]:
diff = np.subtract(X[:,1],X[:,2]) # white rating - black rating
X = np.delete(X,[1,2],axis=1)
X = np.column_stack((X,diff))
print(X)


[[  13    5  309]
 [  16    4   61]
 [  61    3   -4]
 ...
 [  35    3  -67]
 [ 109    4  133]
 [  78    3 -104]]


In [10]:
# Here training and test data is split

In [11]:

X_train , X_test, Y_train, Y_test = train_test_split(
X,Y,test_size=0.05,random_state=0)
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,Y_train)
print(X_train)
print(Y_train)

[[  17    3 -168]
 [  26    4 -398]
 [  61    7   65]
 ...
 [  51    3 -202]
 [  46    4 -227]
 [  27    4 -236]]
[['black']
 ['black']
 ['white']
 ...
 ['white']
 ['black']
 ['black']]


In [12]:
# Score is measured , which is accuracy percentage of the model applied on the test data we split earlier

In [13]:
score = clf.score(X_test, Y_test)
print(score)

0.7587238285144566
